/*
  Baltic Adventure 2026 — canonical trip data (GENERATED by assemble.py).
  window.TRIP drives the whole guide and loads offline from file://.
  To change content: edit assemble.py (facts/schedules/notes/packing) or
  fetch_photos.py (images), then run `python assemble.py`. Confirmed booking
  numbers/costs are real; anything labeled a recommendation is a suggestion.
*/
window.TRIP = {
  "meta": {
    "title": "Baltic Adventure 2026",
    "subtitle": "Michael & Grace's Complete Travel Guide",
    "dates": "July 8–19, 2026",
    "route": "Helsinki · Tallinn · Riga · Vilnius",
    "theme": "Hidden rooms, medieval streets, grand hotels, candlelit cellars, castles, and Baltic countryside",
    "travelers": [
      "Michael",
      "Grace"
    ],
    "booking_ref": "XLOIRG",
    "currency_note": "All four countries use the euro (€). USD figures are approximate.",
    "updated": "2026-06-25"
  },
  "flights": [
    {
      "leg": "Outbound",
      "date": "2026-07-08",
      "date_label": "Wed, Jul 8",
      "flight": "AF3551",
      "operated_by": "Delta",
      "from": "Salt Lake City (SLC)",
      "to": "Paris (CDG)",
      "depart": "3:35 PM",
      "arrive": "9:30 AM (+1, Jul 9)",
      "seat": "",
      "cabin": "Main Cabin",
      "baggage": "1 × 23 kg checked",
      "status": "OK",
      "notes": "Departure day. Leave a comfortable airport buffer."
    },
    {
      "leg": "Connection",
      "date": "2026-07-09",
      "date_label": "Thu, Jul 9",
      "flight": "AF1070",
      "operated_by": "Air France",
      "from": "Paris (CDG)",
      "to": "Helsinki (HEL)",
      "depart": "12:35 PM",
      "arrive": "4:40 PM",
      "seat": "15A",
      "cabin": "Main Cabin",
      "baggage": "1 × 23 kg checked",
      "status": "OK",
      "notes": "Arrive Helsinki 4:40 PM — taxi or tram to Hotel Lilla Roberts, easy night."
    },
    {
      "leg": "Return",
      "date": "2026-07-19",
      "date_label": "Sun, Jul 19",
      "flight": "KL2844",
      "operated_by": "airBaltic",
      "from": "Vilnius (VNO)",
      "to": "Amsterdam (AMS)",
      "depart": "7:50 AM",
      "arrive": "9:15 AM",
      "seat": "",
      "cabin": "",
      "baggage": "1 × 23 kg checked",
      "status": "OK",
      "notes": "Very early departure — target airport arrival ~5:30 AM."
    },
    {
      "leg": "Connection",
      "date": "2026-07-19",
      "date_label": "Sun, Jul 19",
      "flight": "KL6027",
      "operated_by": "Delta",
      "from": "Amsterdam (AMS)",
      "to": "Salt Lake City (SLC)",
      "depart": "10:50 AM",
      "arrive": "1:08 PM",
      "seat": "",
      "cabin": "",
      "baggage": "1 × 23 kg checked",
      "status": "OK",
      "notes": "Home directly from the Vilnius routing — no Helsinki backtrack."
    }
  ],
  "ticket": {
    "passenger_on_ticket": "Michael Robson",
    "ticket_number": "057 236 023 779 2",
    "total_cost": "USD 1,596.73",
    "booking_ref": "XLOIRG",
    "open_item": "Verify Grace has a SEPARATELY ISSUED ticket — the uploaded e-ticket lists only Michael."
  },
  "hotels": [
    {
      "id": "lilla",
      "city": "Helsinki",
      "name": "Hotel Lilla Roberts",
      "website": "https://lillaroberts.com/",
      "address": "Pieni Roobertinkatu 1, 00130 Helsinki, Finland",
      "phone": "",
      "email": "",
      "checkin": "2026-07-09",
      "checkout": "2026-07-10",
      "nights": 1,
      "room": "",
      "rate": "",
      "confirmation": "Confirmed by Preferred Hotels",
      "extra_ref": "I Prefer Member #: PHWABARVT3",
      "cost": "EUR 147.90 / ≈ USD 168.06",
      "payment": "Card ending 3002",
      "status": "Confirmed",
      "why": "Arrival night and recovery before the ferry to Tallinn. A jewel-box Art Deco hotel in the Design District — exactly the kind of room you like to step into tired and feel held.",
      "purpose": "Arrival / recovery",
      "nearby_coffee": "Hotel's own Krog Roba bar & restaurant; cafés along Iso Roobertinkatu pedestrian street.",
      "nearby_stumble": "Design District lanes, Esplanadi park, Market Square & Old Market Hall (Vanha Kauppahalli), Diana Park.",
      "essentials": "Pharmacy (Apteekki) and groceries (K-Market / Alepa) within a few blocks on Iso Roobertinkatu; ATMs (Otto.) nearby.",
      "notes": "One night only — don't overplan. Drop bags, shower, wander to dinner.",
      "history": "Built in 1909 by architect Selim A. Lindqvist as an electricity substation (completed in its present form in 1931), the building powered Helsinki for decades, then housed the city police until 2012. It reopened as Hotel Lilla Roberts in 2015, in the heart of the Design District.",
      "style": "1920s–30s Art Deco — dark tones, geometric motifs, brass and gold — inside a former power station, with modern Nordic touches.",
      "restaurant": "Krog Roba — casual Nordic dining in the old police-station premises (weekend brunch ~12:30–15:00).",
      "bar": "Lilla e — an intimate cocktail bar known for inventive, off-menu drinks.",
      "spa": null,
      "breakfast": "Daily buffet with Finnish touches — pancakes, local berries, fresh-baked bread — in the restaurant.",
      "checkin_tips": "Check-in from 15:00, out by 12:00. Ask for a quieter courtyard-facing room and request the Art Deco design-feature rooms.",
      "parking": "No large in-house garage; staff direct you to nearby public garages in Kaartinkaupunki/Erottaja (pay, no booking). On-street is metered and limited.",
      "taxi_note": "Taxis pull up on Pieni Roobertinkatu directly outside, or reception calls one; Erottaja taxi rank is a 3–5 min walk.",
      "best_evening_walk": "From the door, east to Korkeavuorenkatu, north to Kasarmitori square, then to the Esplanadi promenade — a short Design-District loop back via Erottajankatu.",
      "nearby_hidden": "Design boutiques and galleries along Pieni Roobertinkatu and Fredrikinkatu; the leafy Kasarmitori square a couple of minutes north.",
      "photo": "hotel_lilla"
    },
    {
      "id": "telegraaf",
      "city": "Tallinn",
      "name": "Hotel Telegraaf, Autograph Collection",
      "website": "https://www.telegraafhotel.com/",
      "address": "Vene 9, 10123 Tallinn Old Town, Estonia",
      "phone": "+372 600 0600",
      "email": "",
      "checkin": "2026-07-10",
      "checkout": "2026-07-14",
      "nights": 4,
      "room": "",
      "rate": "",
      "confirmation": "93263159",
      "extra_ref": "",
      "cost": "EUR 1,415.00 total",
      "payment": "",
      "status": "Confirmed",
      "why": "Your main 'stumble' base inside Tallinn's medieval core — a polished historic hotel on Vene Street, steps from St. Catherine's Passage. (The alternative once considered was the Schlössle Hotel, whose fireplace lounge is still worth a non-guest visit.)",
      "purpose": "Tallinn Old Town base (4 nights)",
      "nearby_coffee": "Café Maiasmokk (oldest café in Tallinn, ~3 min walk); Kehrwieder on Town Hall Square.",
      "nearby_stumble": "Vene Street, St. Catherine's Passage, Pikk Street, Town Hall Square — all on the doorstep.",
      "essentials": "Pharmacies (Apteek) and Rimi/Coop groceries around Viru and Town Hall Square; ATMs throughout Old Town.",
      "notes": "Old Town location means cobblestones — pack comfortable shoes. Telegraaf's own bar is a fine nightcap room.",
      "history": "Set in an 1878 building that was once Tallinn's central telegraph exchange (hence the name), restored and opened as Hotel Telegraaf in 2007. Now an 82-room Marriott Autograph Collection property arranged around a courtyard, keeping its vaulted ceilings and period architecture.",
      "style": "Restored 19th-century building blending classical elegance with contemporary boutique design.",
      "restaurant": "Restaurant Tchaikovsky — upscale, Michelin-listed French cuisine with a Russian accent, under a glazed pavilion.",
      "bar": "The Tchaikovsky lobby bar — wines and cocktails in an elegant room.",
      "spa": "Elemis Telegraaf Spa — indoor pool, hot tub, sauna, steam bath, and treatments.",
      "breakfast": "Grand buffet (included) in Tchaikovsky, with an 'Estonian corner' of local dishes; go earlier for a quieter, fuller buffet.",
      "checkin_tips": "Check-in ~15:00–16:00, out by 12:00. Mention Marriott Bonvoy for possible upgrades; ask for a courtyard-side room for quiet.",
      "parking": "Private valet ~€30/day — important, because Vene is inside the restricted Old Town where independent parking is tightly limited. Let the hotel take the car.",
      "taxi_note": "Old Town vehicle access is restricted; taxis/Bolt usually meet guests at the edge of the pedestrian zone near Viru Gate. Reception arranges it.",
      "best_evening_walk": "From Vene 9, north past St. Catherine's Passage, cut to Müürivahe, then to Town Hall Square (~2–3 min) and loop back via Pikk.",
      "nearby_hidden": "St. Catherine's Passage (Katariina käik), a medieval lane of artisan workshops just off Vene; the Dominican Monastery a minute away.",
      "photo": "hotel_telegraaf"
    },
    {
      "id": "grandpalace",
      "city": "Riga",
      "name": "Grand Palace Hotel",
      "website": "https://www.grandpalaceriga.com",
      "address": "Pils Street 12, Riga LV-1050, Latvia",
      "phone": "+371 6704 4000",
      "email": "info@grandpalaceriga.com",
      "checkin": "2026-07-14",
      "checkout": "2026-07-17",
      "nights": 3,
      "room": "Superior King",
      "rate": "Prepay & Save",
      "confirmation": "Room confirmation 48469SG014613",
      "extra_ref": "Itinerary number 22402B8775206",
      "cost": "EUR 697.84 (incl. taxes & fees)",
      "payment": "",
      "status": "Confirmed",
      "why": "Riga Old Town at its most refined — an old-world grand hotel a short walk from the Art Nouveau district and the city's candlelit cellars. The peak 'unplanned jaw-dropping room' city, and this is the room to come home to.",
      "purpose": "Riga Old Town / Art Nouveau / cellar base (3 nights)",
      "nearby_coffee": "Hotel's own Orangerie / bar; cafés around Doma laukums (Dome Square) a few minutes away.",
      "nearby_stumble": "Old Town lanes toward the Dome Cathedral and House of the Black Heads; Art Nouveau on Alberta & Elizabetes iela ~15 min walk.",
      "essentials": "Pharmacies (Aptieka — Mēness aptieka) and Rimi groceries nearby; ATMs around Old Town.",
      "notes": "Verify parking before car pickup on Jul 16 — Old Town access is restricted; ask the hotel about its garage or a nearby lot.",
      "history": "A landmark 1877 building that began as a bank — the chandelier-lit lobby was once its banking hall — on Pils iela in the heart of Riga's Old Town. Today a 56-room five-star boutique, the only Latvian member of Small Luxury Hotels of the World, with interiors styled by Andrew Martin.",
      "style": "Restored 1877 historicist bank building with contemporary boutique interiors over a classical shell.",
      "restaurant": "Seasons Restaurant — MICHELIN-Guide fine dining with menus inspired by iconic artworks; breakfast in the Orangerie conservatory.",
      "bar": "Pils Bar — a clubby, trophy-and-art-filled room whose bartenders have served here 25+ years.",
      "spa": "Wellness rather than full spa: a private-use sauna, 24-hour gym, and treatments on request.",
      "breakfast": "Served in the light-filled Orangerie hall, with eggs cooked to order — go before the morning rush.",
      "checkin_tips": "Check-in from 14:00, out by 12:00. Only 56 rooms — request a quieter upper-floor or courtyard room, and have the concierge pre-arrange Old Town parking.",
      "parking": "No large garage at the door; the hotel arranges nearby garage parking (~€30/day, book ahead). Pils iela is in the restricted Old Town zone — coordinate drop-off with reception.",
      "taxi_note": "Because of Old Town traffic limits, taxis/Bolt pick up at the nearest permitted street edge; reception calls a cab and points you to the spot.",
      "best_evening_walk": "From the door, to Riga Castle and the Daugava riverfront, then back through Mazā Pils iela past the 'Three Brothers' to Dome Square and Riga Cathedral.",
      "nearby_hidden": "The 'Three Brothers' (Trīs brāļi), Riga's oldest houses, a minute away; the quiet gardens around Riga Castle just down the street.",
      "photo": "hotel_grandpalace"
    },
    {
      "id": "pacai",
      "city": "Vilnius",
      "name": "Hotel PACAI",
      "website": "https://www.hotelpacai.com/",
      "address": "Didžioji Street 7, LT-01128 Vilnius, Lithuania",
      "phone": "+370 5 277 0000",
      "email": "reservations@hotelpacai.com",
      "checkin": "2026-07-17",
      "checkout": "2026-07-19",
      "nights": 2,
      "room": "Superior room, double",
      "rate": "Flexible",
      "confirmation": "79121SG051053",
      "extra_ref": "Itinerary number 5154B26337290",
      "cost": "EUR 534.00 (incl. taxes)",
      "payment": "",
      "status": "Confirmed — verify occupancy",
      "why": "A 17th-century palazzo turned design hotel on Didžioji Street, with a hidden courtyard and a vaulted feel. Vilnius magic hides behind archways, and PACAI is one of them.",
      "purpose": "Vilnius Old Town base (2 nights)",
      "nearby_coffee": "Hotel's own Nineteen18 restaurant/bar; cafés along Pilies and Didžioji streets.",
      "nearby_stumble": "Pilies Street spine, Town Hall Square, courtyards off Didžioji, and Užupis just across the river.",
      "essentials": "Pharmacies (Vaistinė) and groceries (IKI / Rimi) around the Old Town; ATMs nearby.",
      "notes": "OPEN ITEM: screenshot showed '1 Adult.' Confirm the booking is for 2 adults / Grace included before arrival.",
      "history": "Set in the Baroque Pac Palace on Didžioji (1677, on 15th-century foundations) — once the grandest aristocratic residence in the Grand Duchy of Lithuania, home of the Pac family and decorated by Italian masters Perti and Palloni. Fully restored and reopened as the 104-room Hotel PACAI in 2018 (a Design Hotels member), preserving original frescoes alongside bold contemporary design.",
      "style": "17th-century Baroque palace restored with bold contemporary, Scandinavian-modern interiors.",
      "restaurant": "Nineteen18 — fine-dining tasting menus (Michelin-recognized); the former stables house the 14Horses all-day brasserie.",
      "bar": "The palace bar serves cocktails in the historic setting alongside 14Horses.",
      "spa": "A spa offering treatments plus relaxation and beauty packages within the hotel.",
      "breakfast": "Served in the 14Horses brasserie in the converted stables — a design-forward space; go a touch earlier on busy mornings.",
      "checkin_tips": "Check-in from 15:00, out by 12:00. Ask for a room showing original frescoes or Baroque detail, and confirm valet parking in advance.",
      "parking": "Courtyard valet parking (~€75/day) or limited street parking; Didžioji is in the restricted Old Town, so valet is simplest.",
      "taxi_note": "Taxis/Bolt reach the Didžioji frontage or nearby Town Hall Square (Rotušės aikštė), an easy pickup point a minute away.",
      "best_evening_walk": "From the door, south past the Town Hall, up Aušros Vartų to the Gates of Dawn chapel, then back north along Didžioji toward the Cathedral.",
      "nearby_hidden": "St. Casimir's Church and the Baroque side lanes off Didžioji; artsy Literatų street (its wall of literary plaques) toward Užupis.",
      "photo": "hotel_pacai"
    }
  ],
  "car": {
    "vendor": "EconomyBookings",
    "website": "https://www.economybookings.com/",
    "booking_number": "B41497753",
    "vehicle": "Volkswagen Polo Automatic (or similar economy)",
    "transmission": "Automatic",
    "seats": 5,
    "luggage": 2,
    "ac": true,
    "driver": "Michael Robson",
    "pickup": {
      "date": "2026-07-16",
      "time": "12:00 PM",
      "location": "Riga Airport (RIX)"
    },
    "dropoff_current": {
      "date": "2026-07-21",
      "time": "1:00 PM",
      "location": "Vilnius Airport (VNO)"
    },
    "dropoff_should_be": "Jul 19 very early at VNO (before the 7:50 AM flight) OR Jul 18 evening at VNO + taxi to airport Jul 19.",
    "cost_estimate": "Not shown on screenshot; Michael estimated ≈ USD 500–600.",
    "status": "Confirmed — return date WRONG, must fix",
    "open_items": [
      "URGENT: Return date currently Jul 21 — flight departs Jul 19 at 7:50 AM. Change to Jul 19 early, or return Jul 18 evening.",
      "Confirm cross-border driving Latvia → Lithuania is explicitly allowed/included.",
      "Confirm one-way drop (RIX pickup → VNO return) is included in the quote.",
      "Confirm automatic transmission in writing.",
      "Check insurance deductible and whether a credit-card CDW applies in Latvia & Lithuania.",
      "Confirm after-hours / early-morning return procedure at VNO."
    ]
  },
  "open_items": [
    {
      "priority": "critical",
      "text": "Verify Grace has a separately issued flight ticket (e-ticket lists only Michael).",
      "done": false
    },
    {
      "priority": "critical",
      "text": "Correct rental car return: change Jul 21 → Jul 19 (early) or Jul 18 evening at VNO.",
      "done": false
    },
    {
      "priority": "critical",
      "text": "Confirm Hotel PACAI is booked for 2 adults, not 1 adult.",
      "done": false
    },
    {
      "priority": "high",
      "text": "Book Helsinki → Tallinn ferry (Tallink) for Jul 10, morning/midday.",
      "done": false
    },
    {
      "priority": "high",
      "text": "Book Tallinn → Riga transport (Lux Express bus) for Jul 14.",
      "done": false
    },
    {
      "priority": "high",
      "text": "Confirm car rental includes cross-border Latvia→Lithuania and one-way drop-off.",
      "done": false
    },
    {
      "priority": "medium",
      "text": "Confirm after-hours / early return procedure at Vilnius Airport (VNO).",
      "done": false
    },
    {
      "priority": "medium",
      "text": "Check parking near Grand Palace Riga and Hotel PACAI Vilnius.",
      "done": false
    },
    {
      "priority": "medium",
      "text": "Download offline Google Maps for Finland, Estonia, Latvia, Lithuania.",
      "done": false
    },
    {
      "priority": "medium",
      "text": "Add all bookings to the calendar.",
      "done": false
    },
    {
      "priority": "low",
      "text": "Confirm automatic transmission in writing on the car booking.",
      "done": false
    },
    {
      "priority": "low",
      "text": "Check insurance deductible / credit-card CDW coverage for LV & LT.",
      "done": false
    }
  ],
  "days": [
    {
      "n": 0,
      "date": "2026-07-08",
      "date_label": "Wed, Jul 8",
      "city": "In flight",
      "sleep": "Overnight on the plane",
      "transport": "SLC → Paris (AF3551, dep 3:35 PM)",
      "theme": "Departure day. The trip begins the moment you leave for the airport.",
      "morning": "Final packing and the before-departure checklist. Double-check passports, the Air France booking ref (XLOIRG), and that bags are within 23 kg.",
      "afternoon": "Depart Salt Lake City 3:35 PM. Settle in for the long leg to Paris.",
      "evening": "Sleep on the plane if you can — Helsinki is +9 hours and you land tomorrow afternoon.",
      "reservation": "Flight ticket XLOIRG · 1 × 23 kg checked bag each.",
      "stumble": "",
      "food": "Eat a real meal at SLC before boarding; airline food is a bonus, not a plan.",
      "backup": "If the SLC→CDG leg slips, the CDG→HEL connection (12:35 PM Jul 9) has a buffer, but know your rebooking options.",
      "maps": [],
      "dont_overplan": false,
      "schedule": [
        [
          "Afternoon",
          "Arrive SLC airport with a comfortable buffer"
        ],
        [
          "3:35 PM",
          "Depart SLC → Paris (AF3551)"
        ],
        [
          "Evening",
          "Dinner aboard; try to sleep — Helsinki is +9 hours"
        ]
      ],
      "notes": {
        "michael": "Don't work the whole flight. The trip starts now — close the laptop after one glass of wine.",
        "grace": null,
        "together": "Set your watches to Helsinki time the moment you board. The trip begins when you decide it does."
      }
    },
    {
      "n": 1,
      "date": "2026-07-09",
      "date_label": "Thu, Jul 9",
      "city": "Helsinki",
      "sleep": "Hotel Lilla Roberts",
      "transport": "Paris → Helsinki (AF1070, arr 4:40 PM); taxi or tram to hotel",
      "theme": "Land softly. Recover. No hard scheduling tonight.",
      "morning": "In transit — Paris CDG connection, depart 12:35 PM. Seat 15A on the Helsinki leg.",
      "afternoon": "Arrive Helsinki 4:40 PM. Taxi (~30 min) or the train + tram to Lilla Roberts. Check in, shower, reset.",
      "evening": "Easy harbor-side wander and an unhurried dinner near the hotel. You've been traveling 24 hours — let it be gentle.",
      "reservation": "Hotel Lilla Roberts — 1 night, EUR 147.90. I Prefer #PHWABARVT3.",
      "stumble": "Drift down Iso Roobertinkatu, cut to the Esplanadi promenade, and look in at the Old Market Hall (Vanha Kauppahalli) if it's still open. Don't force it — it's a stretch-your-legs night.",
      "food": "Dinner near the hotel: Savotta (rustic Finnish, by the cathedral) or the hotel's own Krog Roba. Keep it simple.",
      "backup": "Rain: Esplanadi cafés, the Old Market Hall, or just the hotel bar. Jet-lagged is allowed.",
      "maps": [
        "Esplanadi Helsinki",
        "Market Square Helsinki",
        "Old Market Hall Helsinki",
        "Design District Helsinki"
      ],
      "dont_overplan": true,
      "schedule": [
        [
          "12:35 PM",
          "Depart Paris → Helsinki (AF1070, seat 15A)"
        ],
        [
          "4:40 PM",
          "Land Helsinki"
        ],
        [
          "5:15 PM",
          "Taxi/tram to Hotel Lilla Roberts; check in, shower, reset"
        ],
        [
          "6:45 PM",
          "Slow wander — Iso Roobertinkatu to the Esplanadi promenade"
        ],
        [
          "7:45 PM",
          "Easy dinner near the hotel (Savotta, or Krog Roba in-house)"
        ],
        [
          "9:30 PM",
          "Nightcap at Lilla e, then sleep — it's still light out, ignore it"
        ]
      ],
      "notes": {
        "michael": "Resist the urge to 'see Helsinki' tonight. You've been traveling 24 hours; one gentle loop and a good dinner is the whole assignment.",
        "grace": "The light barely sets in July here — don't let it trick you into staying up. A short walk, then rest.",
        "together": "Tonight is for landing softly, not sightseeing. Let Helsinki be a gentle on-ramp."
      }
    },
    {
      "n": 2,
      "date": "2026-07-10",
      "date_label": "Fri, Jul 10",
      "city": "Helsinki → Tallinn",
      "sleep": "Hotel Telegraaf, Tallinn",
      "transport": "Tallink ferry Helsinki → Tallinn (~2 hrs)",
      "theme": "Cross the gulf and step into the medieval core.",
      "morning": "Relaxed checkout from Lilla Roberts. Coffee, maybe a last look at Market Square, then to the West Terminal for the ferry.",
      "afternoon": "Tallink ferry to Tallinn (~2 hours). Arrive, walk or short taxi to Hotel Telegraaf on Vene Street, check into your 4-night home.",
      "evening": "First Old Town drift: Town Hall Square, Pikk Street, Vene Street. Let the medieval streets do the work.",
      "reservation": "Hotel Telegraaf — 4 nights, conf. 93263159. BOOK the Tallink ferry in advance.",
      "stumble": "From the terminal you'll come up into the Old Town walls — follow the lanes that look oldest. St. Catherine's Passage at dusk is the first 'oh' moment.",
      "food": "Dinner in Old Town — Rataskaevu 16 (book ahead) or Lore Bistroo. A nightcap in the Telegraaf bar.",
      "backup": "Rough water or rain: ferries run regardless; just stay covered between terminal and hotel.",
      "maps": [
        "Tallink West Terminal Helsinki",
        "Hotel Telegraaf Tallinn",
        "Town Hall Square Tallinn",
        "St Catherine's Passage Tallinn"
      ],
      "dont_overplan": false,
      "schedule": [
        [
          "8:30 AM",
          "Breakfast at the hotel; relaxed checkout"
        ],
        [
          "10:00 AM",
          "Last look at Market Square / Old Market Hall"
        ],
        [
          "11:30 AM",
          "To the West Terminal for the Tallink ferry"
        ],
        [
          "12:30 PM",
          "Ferry to Tallinn (~2 hrs) — coffee on deck"
        ],
        [
          "3:00 PM",
          "Arrive; to Hotel Telegraaf on Vene, check in"
        ],
        [
          "5:00 PM",
          "First Old Town drift — Town Hall Square, Pikk, Vene"
        ],
        [
          "8:00 PM",
          "Dinner (Rataskaevu 16 — book ahead), nightcap at the Telegraaf bar"
        ]
      ],
      "notes": {
        "michael": "Book the ferry a few days out, not the morning of. Get a window seat on the way over — the approach to Tallinn's spires is the first 'wow.'",
        "grace": "St. Catherine's Passage at dusk on the first night is pure magic — make sure tonight's wander goes through it.",
        "together": "You're trading a modern Nordic capital for a medieval one in two hours. Let the change of texture land."
      }
    },
    {
      "n": 3,
      "date": "2026-07-11",
      "date_label": "Sat, Jul 11",
      "city": "Tallinn",
      "sleep": "Hotel Telegraaf",
      "transport": "On foot",
      "theme": "The pure Tallinn stumble day. This is what you came for.",
      "morning": "Start at Maiasmokk for coffee and marzipan, then wander Vene and Pikk with no agenda.",
      "afternoon": "Hidden courtyards, cellar cafés, the Master's Courtyard (Meistrite Hoov). Duck into Pierre Chocolaterie. Let one lane lead to the next.",
      "evening": "St. Catherine's Passage after dark; a fireplace-lounge moment — the Schlössle Hotel lounge as a non-guest, or the Telegraaf bar.",
      "reservation": "None required. Keep it open.",
      "stumble": "TODAY IS THE STUMBLE. No checklist — follow the cobblestones, the smell of coffee, the open door. The 'best hidden room' of the trip is probably found today.",
      "food": "Café Maiasmokk, Kehrwieder (Saiakang lane), Kofeman, Loulou for breakfast. Dinner: Rataskaevu 16 if not done.",
      "backup": "Rain makes the cellar cafés better, not worse. This is a rain-proof day.",
      "maps": [
        "Cafe Maiasmokk Tallinn",
        "Pierre Chocolaterie Tallinn",
        "Vene Street Tallinn",
        "Pikk Street Tallinn",
        "Schlossle Hotel Tallinn"
      ],
      "dont_overplan": true,
      "schedule": [
        [
          "9:00 AM",
          "Coffee & marzipan at Café Maiasmokk"
        ],
        [
          "9:45 AM",
          "Wander Vene and Pikk with no agenda"
        ],
        [
          "11:00 AM",
          "Master's Courtyard — Pierre Chocolaterie; hidden lanes"
        ],
        [
          "12:30 PM",
          "Lunch wherever you land"
        ],
        [
          "2:30 PM",
          "Cellar cafés; an unhurried Old Town hour"
        ],
        [
          "4:00 PM",
          "Rest at the hotel (this is allowed)"
        ],
        [
          "6:30 PM",
          "Aperitivo — Schlössle fireplace lounge as non-guests, or the Telegraaf bar"
        ],
        [
          "8:00 PM",
          "Dinner, then St. Catherine's Passage after dark"
        ]
      ],
      "notes": {
        "michael": "Skip the hotel breakfast this morning. Walk five minutes to Maiasmokk instead — you'll get a better feel for Tallinn than sitting in the dining room.",
        "grace": "This is a good afternoon to linger over a hot chocolate and a book in a cellar café. Don't rush to the next thing.",
        "together": "Today has no checklist on purpose. The magic of Tallinn comes from turning down the street you didn't plan to walk."
      }
    },
    {
      "n": 4,
      "date": "2026-07-12",
      "date_label": "Sun, Jul 12",
      "city": "Tallinn",
      "sleep": "Hotel Telegraaf",
      "transport": "On foot",
      "theme": "Walls, towers, and viewpoints — with Medieval Days as ambient festival.",
      "morning": "Up to Toompea for the Patkuli and Kohtuotsa viewpoints over the red roofs. Danish King's Garden and the towers along the way.",
      "afternoon": "Kiek in de Kök and the town wall walk. Medieval Days (Jul 10–12) may be winding through the streets — treat it as atmosphere, not a destination.",
      "evening": "Back into St. Catherine's Passage after dark; dinner leaning medieval or modern, your mood.",
      "reservation": "Keep flexible. Olde Hansa needs no booking for a drink; Rataskaevu 16 does for dinner.",
      "stumble": "Medieval Days means costumed lanes and market stalls appearing where they weren't yesterday — wander into it rather than chasing a program.",
      "food": "Dinner: Rataskaevu 16 (modern Estonian) or Olde Hansa (full medieval theatre) if you want to lean in.",
      "backup": "Rain: the towers and Kiek in de Kök are largely indoors; the wall walk can wait.",
      "maps": [
        "Kohtuotsa viewpoint Tallinn",
        "Kiek in de Kok Tallinn",
        "Danish Kings Garden Tallinn",
        "Toompea Tallinn",
        "Rataskaevu 16 Tallinn"
      ],
      "dont_overplan": false,
      "schedule": [
        [
          "9:30 AM",
          "Up to Toompea — Kohtuotsa & Patkuli viewpoints"
        ],
        [
          "10:30 AM",
          "Danish King's Garden and the towers"
        ],
        [
          "11:30 AM",
          "Kiek in de Kök / a stretch of the town wall"
        ],
        [
          "1:00 PM",
          "Lunch; wander into any Medieval Days stalls"
        ],
        [
          "3:30 PM",
          "Quiet hour — coffee or the hotel"
        ],
        [
          "6:00 PM",
          "Drinks; a last look from the viewpoints in evening light"
        ],
        [
          "8:00 PM",
          "Dinner — Olde Hansa for the full medieval night, or modern contrast"
        ]
      ],
      "notes": {
        "michael": "Medieval Days is winding down (Jul 10–12) — treat any costumed lane you cross as a bonus, not a thing to hunt down.",
        "grace": "Catch the Kohtuotsa viewpoint in the soft evening light, not the midday crowd. The red roofs glow.",
        "together": "Walls and towers by day, candlelight by night. Don't over-fill it — leave room to just sit on the wall and look."
      }
    },
    {
      "n": 5,
      "date": "2026-07-13",
      "date_label": "Sun, Jul 13",
      "city": "Tallinn",
      "sleep": "Hotel Telegraaf",
      "transport": "On foot, tram, or a short taxi",
      "theme": "Contrast day — industrial-creative Tallinn outside the walls.",
      "morning": "Telliskivi Creative City and Kalamaja's wooden houses — coffee, design shops, street art. A different texture entirely.",
      "afternoon": "Either the Seaplane Harbour (Lennusadam) maritime museum or Kadriorg Park & Palace and the Fotografiska rooftop.",
      "evening": "Back to Old Town for a last quiet night before Riga. Easy dinner.",
      "reservation": "Optional dinner reservation if you want one — otherwise loose.",
      "stumble": "Kalamaja's back streets are the stumble zone here — wooden facades, tiny galleries, the Balti Jaam market.",
      "food": "Lunch/coffee in Telliskivi; Fotografiska rooftop for a drink; Lore Bistroo or a Kalamaja spot for dinner.",
      "backup": "Rain: Seaplane Harbour and Fotografiska are indoor anchors.",
      "maps": [
        "Telliskivi Creative City Tallinn",
        "Kalamaja Tallinn",
        "Seaplane Harbour Tallinn",
        "Kadriorg Park Tallinn",
        "Fotografiska Tallinn"
      ],
      "dont_overplan": false,
      "schedule": [
        [
          "9:30 AM",
          "Coffee in Telliskivi Creative City; Kalamaja's wooden streets"
        ],
        [
          "11:00 AM",
          "Balti Jaam market; design shops, street art"
        ],
        [
          "1:00 PM",
          "Lunch in Telliskivi"
        ],
        [
          "2:30 PM",
          "Choose one: Seaplane Harbour, or Kadriorg Park & Palace"
        ],
        [
          "5:00 PM",
          "Fotografiska — gallery then the rooftop"
        ],
        [
          "7:30 PM",
          "Last Tallinn dinner; quiet final Old Town night"
        ]
      ],
      "notes": {
        "michael": "Pick ONE big thing this afternoon — Seaplane Harbour or Kadriorg, not both. The point today is texture, not mileage.",
        "grace": "Kalamaja's pastel wooden houses are the prettiest unhurried morning of the trip — bring the camera and dawdle.",
        "together": "Today is the modern counterpoint to four medieval days. A drink on the Fotografiska roof at golden hour is the bookend."
      }
    },
    {
      "n": 6,
      "date": "2026-07-14",
      "date_label": "Mon, Jul 14",
      "city": "Tallinn → Riga",
      "sleep": "Grand Palace Hotel, Riga",
      "transport": "Lux Express bus Tallinn → Riga (~4.5 hrs)",
      "theme": "Move south. Arrive into Riga's Old Town in the evening.",
      "morning": "Checkout from Telegraaf. Coffee, last Old Town look, to the bus station (Tallinn Bus Station / Autobussijaam).",
      "afternoon": "Lux Express to Riga (~4.5 hrs, comfortable coaches with wifi). Arrive, taxi to Grand Palace Hotel, settle in.",
      "evening": "Loose Old Town drift. Riga Black Magic for the riding-bar-and-balsam ritual, the Grand Palace bar, an easy dinner.",
      "reservation": "Grand Palace Hotel — 3 nights, conf. 48469SG014613. BOOK Lux Express in advance.",
      "stumble": "Riga reveals itself slowly from the bus station toward Old Town — let the first cellar door you pass pull you in.",
      "food": "Riga Black Magic (atmosphere + Riga Black Balsam), Grand Palace bar, or a relaxed Old Town dinner. Keep it loose.",
      "backup": "If the bus is delayed, dinner plans flex — Old Town kitchens run late.",
      "maps": [
        "Tallinn Bus Station",
        "Grand Palace Hotel Riga",
        "Riga Black Magic",
        "Riga Old Town"
      ],
      "dont_overplan": false,
      "schedule": [
        [
          "8:30 AM",
          "Breakfast; checkout from Telegraaf"
        ],
        [
          "10:00 AM",
          "To Tallinn Bus Station for Lux Express"
        ],
        [
          "10:30 AM",
          "Coach to Riga (~4.5 hrs) — wifi, hot drinks, watch the forests"
        ],
        [
          "3:30 PM",
          "Arrive Riga; taxi to Grand Palace Hotel, settle in"
        ],
        [
          "5:30 PM",
          "Loose Old Town drift; Riga Black Magic for the balsam ritual"
        ],
        [
          "8:00 PM",
          "Easy dinner, nightcap at the Pils Bar"
        ]
      ],
      "notes": {
        "michael": "Book Lux Express ahead and pick the comfort seats. Don't plan a hard evening — you'll arrive a little road-worn.",
        "grace": null,
        "together": "Riga reveals itself slowly from the bus station inward. Let the first cellar door you pass pull you in."
      }
    },
    {
      "n": 7,
      "date": "2026-07-15",
      "date_label": "Tue, Jul 15",
      "city": "Riga",
      "sleep": "Grand Palace Hotel",
      "transport": "On foot",
      "theme": "The jaw-dropping stumble day. Riga is the peak unplanned-room city.",
      "morning": "Art Nouveau morning: Alberta iela and Elizabetes iela — the most extravagant facades in Europe. Coffee at Art Café Sienna among the period rooms.",
      "afternoon": "Back to Old Town for the cellars: Riga Black Magic, the House of the Black Heads exterior, hidden vaulted bars.",
      "evening": "Rozengrāls — the candlelit medieval cellar — is the one worth reserving. Everything else stays loose.",
      "reservation": "RECOMMENDATION: reserve Rozengrāls for dinner. Leave the rest of the day unplanned.",
      "stumble": "This is Riga's day to ambush you with beauty. Wander between the Art Nouveau district and the Old Town cellars and let the rooms find you.",
      "food": "Art Café Sienna (daytime), Rozengrāls (book), Folkklubs Ala Pagrabs, 3 Pavāru, or Milda for modern Latvian.",
      "backup": "Rain: the cellars and Art Nouveau interiors (Riga Art Nouveau Museum on Alberta iela) are the play.",
      "maps": [
        "Alberta iela Riga",
        "Elizabetes iela Riga",
        "Art Cafe Sienna Riga",
        "Rozengrals Riga",
        "House of the Black Heads Riga"
      ],
      "dont_overplan": true,
      "schedule": [
        [
          "9:00 AM",
          "Breakfast in the Orangerie"
        ],
        [
          "10:00 AM",
          "Art Nouveau morning — Alberta iela, then Elizabetes iela; look UP"
        ],
        [
          "11:30 AM",
          "Coffee at Art Café Sienna among the period rooms"
        ],
        [
          "1:00 PM",
          "Lunch; drift back toward Old Town"
        ],
        [
          "3:00 PM",
          "Old Town cellars; House of the Black Heads; hidden vaulted bars"
        ],
        [
          "5:00 PM",
          "Rest before dinner"
        ],
        [
          "7:30 PM",
          "Rozengrāls — the candlelit medieval cellar (reserve this)"
        ],
        [
          "9:30 PM",
          "A slow walk home through the lit lanes"
        ]
      ],
      "notes": {
        "michael": "Reserve Rozengrāls and nothing else. Riga's whole gift today is the unplanned room you stumble into between the two booked moments.",
        "grace": "Alberta iela is the most beautiful street of the trip. Walk it slowly, twice. This is your jaw-drop morning.",
        "together": "Two textures, one day: extravagant facades above, candlelit cellars below. This is the peak 'unplanned beauty' city — let it ambush you."
      }
    },
    {
      "n": 8,
      "date": "2026-07-16",
      "date_label": "Wed, Jul 16",
      "city": "Riga + countryside",
      "sleep": "Grand Palace Hotel (final Riga night)",
      "transport": "Rental car from RIX 12:00 PM",
      "theme": "Pick up the car at noon. One or two countryside stops — not a marathon.",
      "morning": "Slow Riga morning. Taxi to Riga Airport (RIX) for the 12:00 PM car pickup. Inspect the car, photograph any damage, confirm cross-border + automatic in writing.",
      "afternoon": "Drive into the Gauja valley: Turaida Castle (the red-brick tower over the river) and Sigulda. Cēsis only if time allows — don't force it from a noon start.",
      "evening": "Back to Riga and the Grand Palace for your final Riga night. Park per the hotel's guidance.",
      "reservation": "Car pickup confirmed (B41497753). Grand Palace night 3.",
      "stumble": "Turaida and the Gauja overlooks are the 'beauty you stumble into' in countryside form — quiet, green, medieval.",
      "food": "A simple lunch in Sigulda; dinner back in Riga (Old Town, your pick).",
      "backup": "If pickup runs late or weather turns, pick ONE stop (Turaida) and keep it relaxed. The car's real job starts tomorrow.",
      "maps": [
        "Riga Airport RIX",
        "Turaida Castle",
        "Sigulda",
        "Gauja National Park",
        "Cesis Latvia"
      ],
      "dont_overplan": true,
      "schedule": [
        [
          "9:30 AM",
          "Slow Riga morning; coffee"
        ],
        [
          "11:15 AM",
          "Taxi to Riga Airport (RIX)"
        ],
        [
          "12:00 PM",
          "Pick up the car — inspect, photograph, confirm cross-border + automatic in writing"
        ],
        [
          "1:00 PM",
          "Drive to the Gauja valley"
        ],
        [
          "2:00 PM",
          "Turaida Castle — climb the tower for the river view"
        ],
        [
          "3:30 PM",
          "Sigulda overlook (Cēsis only if you're full of energy)"
        ],
        [
          "6:00 PM",
          "Back to Riga; park per the hotel's guidance"
        ],
        [
          "7:30 PM",
          "Final Riga dinner, your pick"
        ]
      ],
      "notes": {
        "michael": "Noon pickup means ONE castle done well, not three rushed. Turaida + a Sigulda overlook is plenty. Photograph the car before you drive off.",
        "grace": "Turaida's red tower over the green Gauja valley is the countryside version of 'stumbling into beauty.' Linger at the top.",
        "together": "Don't make this a marathon. One castle, one overlook, home for a good dinner. The car's real day is tomorrow."
      }
    },
    {
      "n": 9,
      "date": "2026-07-17",
      "date_label": "Thu, Jul 17",
      "city": "Riga → Vilnius",
      "sleep": "Hotel PACAI, Vilnius",
      "transport": "Drive Riga → Hill of Crosses → Vilnius (~4.5 hrs + stop)",
      "theme": "The big countryside transfer. One iconic stop on the way.",
      "morning": "Check out of the Grand Palace. Drive south toward the Lithuanian border.",
      "afternoon": "Hill of Crosses near Šiauliai — thousands of crosses on a low hill, eerie and moving. ~30–45 min there, then on to Vilnius.",
      "evening": "Arrive Vilnius, check into Hotel PACAI, drop bags. Easy first wander: Pilies Street and the courtyards off Didžioji.",
      "reservation": "Hotel PACAI — 2 nights, conf. 79121SG051053. (Confirm 2 adults.)",
      "stumble": "Vilnius hides its magic behind archways — push open the courtyard gates off Pilies and Didžioji and see what's inside.",
      "food": "Easy first-night dinner near PACAI — Lokys (game, medieval cellar) or a Pilies Street spot. Coffee at Eskedar or Italala.",
      "backup": "If the drive runs long, skip any extra stop and make Hill of Crosses the single one.",
      "maps": [
        "Hill of Crosses Siauliai",
        "Hotel PACAI Vilnius",
        "Pilies Street Vilnius",
        "Vilnius Old Town"
      ],
      "dont_overplan": false,
      "schedule": [
        [
          "8:30 AM",
          "Breakfast; checkout from the Grand Palace"
        ],
        [
          "9:30 AM",
          "Drive south toward the Lithuanian border"
        ],
        [
          "12:00 PM",
          "Hill of Crosses near Šiauliai — 30–45 min, quietly"
        ],
        [
          "12:45 PM",
          "Lunch on the road"
        ],
        [
          "3:30 PM",
          "Arrive Vilnius; check into Hotel PACAI, drop bags"
        ],
        [
          "5:00 PM",
          "First wander — Pilies Street, courtyards off Didžioji"
        ],
        [
          "8:00 PM",
          "Easy first-night dinner (Lokys, or a Pilies spot)"
        ]
      ],
      "notes": {
        "michael": "It's a long driving day — make Hill of Crosses the single stop and don't add a second. Arrive Vilnius with energy to wander, not wrung out.",
        "grace": "The Hill of Crosses is strange and moving — give it real quiet, not a quick photo. Then let Vilnius's hidden courtyards lift the mood.",
        "together": "Vilnius hides its magic behind archways. Push open the courtyard gates off Pilies and Didžioji and see what's inside."
      }
    },
    {
      "n": 10,
      "date": "2026-07-18",
      "date_label": "Fri, Jul 18",
      "city": "Vilnius + Trakai",
      "sleep": "Hotel PACAI",
      "transport": "Car (or train) to Trakai (~30 min)",
      "theme": "Island castle by day, hidden Vilnius by evening. Decide the car return.",
      "morning": "Drive to Trakai early or late to dodge crowds — the red-brick castle on its island in Lake Galvė is the picture-postcard of the trip.",
      "afternoon": "Back to Vilnius. Užupis (the self-declared artists' republic), the courtyards off Pilies, Cathedral Square.",
      "evening": "Final dinner — Džiaugsmas, Ertlio Namas, or Grey. Consider Grand Hotel Vilnius afternoon tea earlier if it fits. DECIDE: return the car tonight at VNO or tomorrow at dawn.",
      "reservation": "Decide car-return timing. Pack for the early flight tonight.",
      "stumble": "Užupis is the stumble zone — cross the little bridge, find the constitution on the wall, the galleries, the river benches.",
      "food": "Trakai: try kibinai (the local pastry) lakeside. Vilnius dinner: Džiaugsmas / Ertlio Namas / Lokys / Grey.",
      "backup": "Rain at Trakai: the castle interior is a museum; or skip Trakai and go deep on Vilnius courtyards and Užupis.",
      "maps": [
        "Trakai Castle",
        "Lake Galve Trakai",
        "Uzupis Vilnius",
        "Cathedral Square Vilnius",
        "Vilnius Airport VNO"
      ],
      "dont_overplan": false,
      "schedule": [
        [
          "8:30 AM",
          "Early drive to Trakai (~30 min) to beat the crowds"
        ],
        [
          "9:30 AM",
          "Trakai Island Castle on Lake Galvė; kibinai lakeside"
        ],
        [
          "12:30 PM",
          "Back to Vilnius; lunch"
        ],
        [
          "2:30 PM",
          "Užupis — the bridge, the constitution wall, the galleries"
        ],
        [
          "4:00 PM",
          "Courtyards off Pilies; Cathedral Square"
        ],
        [
          "5:00 PM",
          "Decide & handle the car return (tonight at VNO is the safe play)"
        ],
        [
          "7:30 PM",
          "Final dinner (Džiaugsmas / Ertlio Namas / Grey); pack tonight"
        ]
      ],
      "notes": {
        "michael": "Return the car this evening at VNO and taxi tomorrow — it removes all dawn risk before a 7:50 AM flight. Worth the small hassle tonight.",
        "grace": "Užupis is the trip's last 'stumble' — cross the little bridge, find the constitution on the wall, sit by the river with a glass of something.",
        "together": "Last full day. Castle in the morning, artists' republic in the afternoon, a long dinner. Then pack — the flight is brutally early."
      }
    },
    {
      "n": 11,
      "date": "2026-07-19",
      "date_label": "Sun, Jul 19",
      "city": "Vilnius → home",
      "sleep": "Home (SLC)",
      "transport": "VNO → AMS → SLC (KL2844 dep 7:50 AM)",
      "theme": "Very early departure. Smooth and unhurried beats fast.",
      "morning": "Airport ~5:30 AM. Return the car at VNO (if not done last night), or taxi over. VNO → AMS departs 7:50 AM.",
      "afternoon": "Amsterdam connection (KL6027, dep 10:50 AM) → Salt Lake City, arrive 1:08 PM.",
      "evening": "Home.",
      "reservation": "Flight XLOIRG · 1 × 23 kg checked bag each · passports.",
      "stumble": "",
      "food": "Coffee and something small at VNO; the long way home has meals aboard.",
      "backup": "Build in margin: if anything is unsure about the car return, returning Jul 18 evening + a pre-booked taxi removes all dawn risk.",
      "maps": [
        "Vilnius Airport VNO"
      ],
      "dont_overplan": false,
      "reminders": [
        "Recommended airport arrival ~5:30 AM",
        "Car return reminder",
        "Passports",
        "Baggage 1 × 23 kg each",
        "VNO dep 7:50 AM"
      ],
      "schedule": [
        [
          "5:00 AM",
          "Wake; final room sweep for chargers"
        ],
        [
          "5:30 AM",
          "Taxi / be at Vilnius Airport (VNO)"
        ],
        [
          "7:50 AM",
          "Depart VNO → Amsterdam (KL2844)"
        ],
        [
          "10:50 AM",
          "Amsterdam → Salt Lake City (KL6027)"
        ],
        [
          "1:08 PM",
          "Land SLC — home"
        ]
      ],
      "notes": {
        "michael": "If the car isn't already returned, that's the one thing that can derail the morning. Otherwise: passports, bags, taxi, coffee, done.",
        "grace": null,
        "together": "Don't rush the goodbye. One last coffee, then the long, easy way home. You did the stumble trip right."
      }
    }
  ],
  "transport": [
    {
      "leg": "Helsinki → Tallinn",
      "date": "2026-07-10",
      "mode": "Ferry",
      "vendor": "Tallink",
      "website": "https://www.tallink.com/",
      "target": "Morning / midday",
      "notes": "~2-hour crossing. Book a departure that allows a relaxed Lilla Roberts checkout and a comfortable Telegraaf check-in. Bring your booking on your phone."
    },
    {
      "leg": "Tallinn → Riga",
      "date": "2026-07-14",
      "mode": "Bus",
      "vendor": "Lux Express",
      "website": "https://luxexpress.eu/",
      "target": "Late morning",
      "notes": "~4.5 hrs. Comfortable coaches (wifi, hot drinks). Easier than the train on this route. Private transfer is the alternative if you'd rather not bus."
    },
    {
      "leg": "Riga Airport pickup",
      "date": "2026-07-16",
      "mode": "Rental car",
      "vendor": "EconomyBookings",
      "website": "https://www.economybookings.com/",
      "target": "12:00 PM",
      "notes": "Taxi from Grand Palace to RIX. Inspect & photograph the car; confirm cross-border + automatic in writing."
    },
    {
      "leg": "Riga → Sigulda/Turaida → Riga",
      "date": "2026-07-16",
      "mode": "Rental car",
      "vendor": "—",
      "website": "",
      "target": "Afternoon",
      "notes": "Countryside day trip without changing hotels. Back to Grand Palace for night 3."
    },
    {
      "leg": "Riga → Hill of Crosses → Vilnius",
      "date": "2026-07-17",
      "mode": "Rental car",
      "vendor": "—",
      "website": "",
      "target": "All day",
      "notes": "Main transfer. ~4.5 hrs driving + the Hill of Crosses stop. Arrive Vilnius before evening."
    },
    {
      "leg": "Vilnius / Trakai",
      "date": "2026-07-18",
      "mode": "Rental car",
      "vendor": "—",
      "website": "",
      "target": "Day trip",
      "notes": "Trakai is a ~30-min drive. Decide whether to return the car this evening at VNO."
    },
    {
      "leg": "Vilnius Airport departure",
      "date": "2026-07-19",
      "mode": "Car return / taxi",
      "vendor": "—",
      "website": "",
      "target": "~5:30 AM",
      "notes": "Flight departs 7:50 AM. Return car at VNO very early, or returned Jul 18 evening + taxi."
    }
  ],
  "places": [
    {
      "city": "Helsinki",
      "name": "Savotta",
      "type": "Restaurant",
      "tag": "rec",
      "why": "Rustic, theatrical Finnish food by the cathedral — cozy and characterful.",
      "reserve": "Recommended",
      "website": "https://www.ravintolasavotta.fi/",
      "notes": "Reindeer, archipelago classics.",
      "signature": "Genuine Finnish fare by Senate Square — reindeer roast, lake fish, elk; logging-camp décor",
      "cost_band": "€€€",
      "dress": "Smart casual",
      "reservation_url": "https://ravintolasavotta.fi/en/",
      "after_walk": "Step onto Senate Square and the cathedral's white steps just outside."
    },
    {
      "city": "Helsinki",
      "name": "Shelter",
      "type": "Restaurant",
      "tag": "rec",
      "why": "Intimate neighborhood dining, warm room.",
      "reserve": "Recommended",
      "website": "",
      "notes": ""
    },
    {
      "city": "Helsinki",
      "name": "Old Market Hall (Vanha Kauppahalli)",
      "type": "Market / café",
      "tag": "rec",
      "why": "1889 market hall — coffee, salmon soup, a graze among stalls.",
      "reserve": "No",
      "website": "https://vanhakauppahalli.fi/",
      "notes": "Check hours; closes early evening.",
      "signature": "Historic 1889 waterfront hall — salmon soup, archipelago bread, coffee stalls",
      "cost_band": "€",
      "dress": "Casual",
      "reservation_url": null,
      "after_walk": "Browse the open-air Market Square and the harbour ferries outside.",
      "photo": "helsinki_market"
    },
    {
      "city": "Helsinki",
      "name": "Löyly",
      "type": "Sauna / restaurant",
      "tag": "rec",
      "why": "Architectural seaside sauna + restaurant — very Finnish, very atmospheric.",
      "reserve": "Recommended (sauna)",
      "website": "https://www.loylyhelsinki.fi/",
      "notes": "A bit out from center; book sauna ahead.",
      "signature": "Seaside public sauna with a seasonal Nordic restaurant and Baltic-front terrace",
      "cost_band": "€€",
      "dress": "Casual",
      "reservation_url": "https://www.loylyhelsinki.fi/en",
      "after_walk": "Take the seafront promenade along Hernesaari back toward the city."
    },
    {
      "city": "Helsinki",
      "name": "Krog Roba (Hotel Lilla Roberts)",
      "type": "Bar / restaurant",
      "tag": "hotel",
      "why": "Your hotel's own room — easiest possible jet-lagged dinner.",
      "reserve": "No",
      "website": "https://lillaroberts.com/",
      "notes": "In the hotel."
    },
    {
      "city": "Tallinn",
      "name": "Rataskaevu 16",
      "type": "Restaurant",
      "tag": "rec",
      "why": "Beloved modern Estonian in a candlelit room — the Old Town dinner.",
      "reserve": "Yes — book ahead",
      "website": "https://www.rataskaevu16.ee/",
      "notes": "Popular; reserve early.",
      "signature": "Hearty Estonian — braised elk, oven-baked salmon, free pumpkin bread; the famous chocolate cake",
      "cost_band": "€€",
      "dress": "Smart casual",
      "reservation_url": "https://www.rataskaevu16.ee/",
      "after_walk": "Wander up to Toompea and the Kohtuotsa platform for rooftops over the Old Town."
    },
    {
      "city": "Tallinn",
      "name": "Olde Hansa",
      "type": "Restaurant",
      "tag": "rec",
      "why": "Full medieval theatre — candlelight, costumes, bear and elk. Lean into the theme.",
      "reserve": "Recommended",
      "website": "https://www.oldehansa.ee/",
      "notes": "Touristy but genuinely atmospheric.",
      "signature": "A Hanseatic medieval feast — bear stew in wild-berry sauce, elk, boar; candlelit hall, live period music",
      "cost_band": "€€€",
      "dress": "Smart casual",
      "reservation_url": "https://www.oldehansa.ee/",
      "after_walk": "Step out onto Town Hall Square and the medieval lanes around it.",
      "photo": "rest_oldehansa"
    },
    {
      "city": "Tallinn",
      "name": "Lore Bistroo",
      "type": "Restaurant",
      "tag": "rec",
      "why": "Stylish Kalamaja bistro — the modern contrast to Old Town.",
      "reserve": "Recommended",
      "website": "https://lorebistroo.ee/",
      "notes": "Near Telliskivi.",
      "signature": "Wood-fired modern bistro plates, family-style sharing; Michelin Bib Gourmand, harbour-side at Noblessner",
      "cost_band": "€€",
      "dress": "Casual",
      "reservation_url": "https://www.lorebistroo.ee/en/",
      "after_walk": "Stroll the Noblessner seaside promenade, then toward Kalamaja."
    },
    {
      "city": "Tallinn",
      "name": "Fotografiska rooftop",
      "type": "Café / bar",
      "tag": "rec",
      "why": "Rooftop restaurant atop the photography museum — views + drinks.",
      "reserve": "Recommended",
      "website": "https://www.fotografiska.com/tallinn/",
      "notes": "Pair with the gallery.",
      "signature": "Leaf-to-root seasonal plates with Old Town rooftop views above the photo gallery",
      "cost_band": "€€€",
      "dress": "Smart casual",
      "reservation_url": "https://tallinn.fotografiska.com/en/restaurants/fotografiska-restaurant",
      "after_walk": "Explore the creative Telliskivi quarter and its street art below."
    },
    {
      "city": "Tallinn",
      "name": "Café Maiasmokk",
      "type": "Café",
      "tag": "rec",
      "why": "Tallinn's oldest café (1864) — marzipan, old-world room. A must-coffee.",
      "reserve": "No",
      "website": "https://www.kohvikmaiasmokk.ee/",
      "notes": "On Pikk, steps from Telegraaf.",
      "signature": "Estonia's oldest café (1864) — hand-painted Kalev marzipan, pastries, a century-old interior",
      "cost_band": "€",
      "dress": "Casual",
      "reservation_url": "https://kohvikmaiasmokk.ee/en/",
      "after_walk": "Browse Pikk Street's merchant houses and the Great Guild Hall steps away.",
      "photo": "rest_maiasmokk"
    },
    {
      "city": "Tallinn",
      "name": "Pierre Chocolaterie",
      "type": "Café / chocolate",
      "tag": "rec",
      "why": "Hidden in the Master's Courtyard — a tiny candlelit chocolate room.",
      "reserve": "No",
      "website": "https://www.pierre.ee/",
      "notes": "Meistrite Hoov courtyard.",
      "signature": "Handmade chocolates and hot chocolate in the cobbled Master's Courtyard (Meistrite Hoov)",
      "cost_band": "€",
      "dress": "Casual",
      "reservation_url": null,
      "after_walk": "Linger in the artisan courtyard, then follow Vene to the Dominican Monastery."
    },
    {
      "city": "Tallinn",
      "name": "Kehrwieder (Saiakang)",
      "type": "Café",
      "tag": "rec",
      "why": "Cozy Town Hall Square café down a tiny lane — armchairs and cocoa.",
      "reserve": "No",
      "website": "",
      "notes": "Saiakang passage.",
      "signature": "Cosy Town Hall Square café — cakes, coffee, and big mugs of hot chocolate",
      "cost_band": "€",
      "dress": "Casual",
      "reservation_url": null,
      "after_walk": "Circle Raekoja plats and duck into the medieval side streets."
    },
    {
      "city": "Tallinn",
      "name": "Kofeman",
      "type": "Café",
      "tag": "rec",
      "why": "Good coffee stop while wandering.",
      "reserve": "No",
      "website": "",
      "notes": ""
    },
    {
      "city": "Tallinn",
      "name": "Loulou",
      "type": "Café / breakfast",
      "tag": "rec",
      "why": "Pretty breakfast spot for a slow Old Town morning.",
      "reserve": "No",
      "website": "",
      "notes": ""
    },
    {
      "city": "Tallinn",
      "name": "Schlössle Hotel fireplace lounge",
      "type": "Hotel lounge",
      "tag": "rec",
      "why": "The alternative hotel once considered — drop in as a non-guest for the fireplace room.",
      "reserve": "No (just a drink)",
      "website": "https://www.schlossle-hotel.com/",
      "notes": "Quiet, grand, candlelit."
    },
    {
      "city": "Tallinn",
      "name": "Hotel Telegraaf bar",
      "type": "Hotel bar",
      "tag": "hotel",
      "why": "Your own hotel's bar — the easiest nightcap room.",
      "reserve": "No",
      "website": "https://www.telegraafhotel.com/",
      "notes": "In the hotel."
    },
    {
      "city": "Riga",
      "name": "Rozengrāls",
      "type": "Restaurant",
      "tag": "rec",
      "why": "A genuine medieval cellar lit only by candles — the one Riga dinner to reserve.",
      "reserve": "Yes — reserve",
      "website": "https://www.rozengrals.lv/",
      "notes": "13th-century vaults; book ahead.",
      "signature": "Medieval dining in a vaulted 1293 wine cellar — old-recipe dishes, honey mead, candlelight",
      "cost_band": "€€",
      "dress": "Smart casual",
      "reservation_url": "https://rozengrals.lv/en/",
      "after_walk": "Wind through the lanes to Town Hall Square and the House of the Black Heads."
    },
    {
      "city": "Riga",
      "name": "Riga Black Magic",
      "type": "Bar / café",
      "tag": "rec",
      "why": "Dark, theatrical bar built around Riga Black Balsam — pure atmosphere.",
      "reserve": "No",
      "website": "https://www.melnaismags.lv/",
      "notes": "Try the balsam; also a chocolate shop.",
      "signature": "A mystical apothecary café built around Riga Black Balsam — in hot chocolate, cocktails, and chocolates",
      "cost_band": "€€",
      "dress": "Casual",
      "reservation_url": "https://www.blackmagic.lv/",
      "after_walk": "Walk Kaļķu iela toward the Freedom Monument and the canal park.",
      "photo": "riga_blackheads"
    },
    {
      "city": "Riga",
      "name": "Art Café Sienna",
      "type": "Café",
      "tag": "rec",
      "why": "Coffee among Art Nouveau period rooms in the Alberta iela district.",
      "reserve": "No",
      "website": "",
      "notes": "Pair with the facades walk.",
      "signature": "Elegant Art Nouveau-style café — cakes, breakfasts, coffee near the National Opera",
      "cost_band": "€",
      "dress": "Casual",
      "reservation_url": null,
      "after_walk": "Stroll Bastejkalns park and the canal, then up Alberta iela for the finest façades."
    },
    {
      "city": "Riga",
      "name": "Grand Palace Hotel bar",
      "type": "Hotel bar",
      "tag": "hotel",
      "why": "Your own grand-hotel bar — old-world nightcap.",
      "reserve": "No",
      "website": "https://www.grandpalaceriga.com",
      "notes": "In the hotel."
    },
    {
      "city": "Riga",
      "name": "Milda",
      "type": "Restaurant",
      "tag": "rec",
      "why": "Modern Latvian, warm and personal.",
      "reserve": "Recommended",
      "website": "",
      "notes": "",
      "signature": "Cosy Baltic home-cooking — grey peas with bacon, pelmeni, cepelinai; Michelin Bib Gourmand",
      "cost_band": "€€",
      "dress": "Casual",
      "reservation_url": "https://restoransmilda.lv/",
      "after_walk": "Amble to St. Peter's Church and the medieval heart of the Old Town."
    },
    {
      "city": "Riga",
      "name": "3 Pavāru Restorāns",
      "type": "Restaurant",
      "tag": "rec",
      "why": "'3 Chefs' — inventive tasting cooking, a step up.",
      "reserve": "Recommended",
      "website": "https://www.3pavari.lv/",
      "notes": "",
      "signature": "'Three Chefs' — contemporary Latvian tasting menus, open-kitchen theatre; Michelin-listed",
      "cost_band": "€€€",
      "dress": "Smart casual",
      "reservation_url": "https://www.3pavari.lv/en/",
      "after_walk": "Follow the Jacob's Barracks arcade to the Swedish Gate and old city wall."
    },
    {
      "city": "Riga",
      "name": "Folkklubs Ala Pagrabs",
      "type": "Bar / restaurant",
      "tag": "rec",
      "why": "Cavernous folk-music cellar — local beer, hearty plates, live music.",
      "reserve": "Recommended (eve)",
      "website": "https://www.folkklubs.lv/",
      "notes": "Great cellar atmosphere.",
      "signature": "Folk-club cellar — 30+ Latvian craft beers, house moonshine, hearty fare, live folk music",
      "cost_band": "€",
      "dress": "Casual",
      "reservation_url": "https://folkklubs-ala-pagrabs.tablein.com/en",
      "after_walk": "Cross to the riverside park and views over the Daugava."
    },
    {
      "city": "Riga",
      "name": "Barents",
      "type": "Restaurant",
      "tag": "rec",
      "why": "If you want a splurge — refined seafood-forward room.",
      "reserve": "Yes",
      "website": "",
      "notes": "Splurge option."
    },
    {
      "city": "Vilnius",
      "name": "Džiaugsmas",
      "type": "Restaurant",
      "tag": "rec",
      "why": "Refined modern Lithuanian — a standout final-dinner candidate.",
      "reserve": "Yes",
      "website": "https://dziaugsmas.lt/",
      "notes": "",
      "signature": "Locally-sourced Lithuanian fine dining ('joy') by chef Praškevičius; Michelin-starred tasting menus",
      "cost_band": "€€€",
      "dress": "Smart casual",
      "reservation_url": "https://dziaugsmas.lt/",
      "after_walk": "Wander the Old Town lanes toward the Gates of Dawn and St. Anne's."
    },
    {
      "city": "Vilnius",
      "name": "Ertlio Namas",
      "type": "Restaurant",
      "tag": "rec",
      "why": "Historic Lithuanian recipes in an old townhouse — atmospheric and rooted.",
      "reserve": "Recommended",
      "website": "https://ertlionamas.lt/",
      "notes": "",
      "signature": "Researched historical Lithuanian cuisine in a period house — slow 4–6 course tastings",
      "cost_band": "€€€",
      "dress": "Smart casual",
      "reservation_url": "https://ertlionamas.lt/en",
      "after_walk": "Climb Gediminas' Tower for the view, then down to Cathedral Square."
    },
    {
      "city": "Vilnius",
      "name": "Lokys",
      "type": "Restaurant",
      "tag": "rec",
      "why": "Game restaurant in a 15th-century cellar — beaver, boar, candle glow.",
      "reserve": "Recommended",
      "website": "https://www.lokys.lt/",
      "notes": "Off Pilies/Stiklių.",
      "signature": "Old Town's oldest restaurant (1972) in a 15th-c. house — game and the signature beaver stew, vaulted cellars",
      "cost_band": "€€",
      "dress": "Smart casual",
      "reservation_url": "https://lokys.lt/en/",
      "after_walk": "Lose yourself in the Stiklių glassblowers' lanes toward Town Hall Square."
    },
    {
      "city": "Vilnius",
      "name": "Grey",
      "type": "Restaurant",
      "tag": "rec",
      "why": "Contemporary tasting room for a modern contrast.",
      "reserve": "Yes",
      "website": "",
      "notes": "",
      "signature": "Modern European cooking known for striking grey-hued dishes, on Pilies Street",
      "cost_band": "€€",
      "dress": "Smart casual",
      "reservation_url": "https://www.restoranasgrey.lt/en/",
      "after_walk": "Walk Pilies Street up to Cathedral Square."
    },
    {
      "city": "Vilnius",
      "name": "Grand Hotel Vilnius afternoon tea",
      "type": "Hotel lounge",
      "tag": "rec",
      "why": "Grand-hotel afternoon tea — only if it fits the day.",
      "reserve": "Recommended",
      "website": "",
      "notes": "Optional treat."
    },
    {
      "city": "Vilnius",
      "name": "Eskedar Coffee Bar",
      "type": "Café",
      "tag": "rec",
      "why": "Lovely specialty coffee stop while wandering Old Town.",
      "reserve": "No",
      "website": "",
      "notes": "",
      "signature": "Ethiopian specialty coffee roasted locally — signature espresso and a traditional coffee ceremony",
      "cost_band": "€",
      "dress": "Casual",
      "reservation_url": "https://eskedarcoffee.com/",
      "after_walk": "Sip and stroll Pilies Street's craft stalls toward the university."
    },
    {
      "city": "Vilnius",
      "name": "Italala Caffe",
      "type": "Café",
      "tag": "rec",
      "why": "Cozy café for a courtyard pause.",
      "reserve": "No",
      "website": "",
      "notes": ""
    },
    {
      "city": "Vilnius",
      "name": "Augustas & Barbora Love Story Café",
      "type": "Café",
      "tag": "rec",
      "why": "A romantic, story-themed café — fitting for the two of you.",
      "reserve": "No",
      "website": "",
      "notes": ""
    },
    {
      "city": "Vilnius",
      "name": "Užupis cafés & wine bars",
      "type": "Café / wine",
      "tag": "rec",
      "why": "The artists' republic across the river — riverside wine and benches.",
      "reserve": "No",
      "website": "",
      "notes": "Wander and pick one."
    },
    {
      "city": "Vilnius",
      "name": "Nineteen18 (Hotel PACAI)",
      "type": "Restaurant / bar",
      "tag": "hotel",
      "why": "Your hotel's own restaurant — convenient first or last night.",
      "reserve": "Recommended",
      "website": "https://www.hotelpacai.com/",
      "notes": "In the hotel."
    }
  ],
  "castles": [
    {
      "name": "Turaida Castle",
      "region": "Gauja valley (near Sigulda)",
      "why": "Red-brick 13th-century bishop's castle with a tower over the Gauja valley, in the Turaida reserve.",
      "drive": "~1 hr from Riga",
      "parking": "Paid lot at the museum reserve.",
      "timing": "Jul 16 afternoon",
      "duration": "1.5–2 hrs",
      "photo": "castle_turaida",
      "rec": "KEEP — the anchor stop.",
      "photo_key": "castle_turaida",
      "photo_tip": "Climb the main tower for the river-valley view."
    },
    {
      "name": "Sigulda",
      "region": "Gauja National Park",
      "why": "Gateway town to the Gauja valley — a neo-Gothic New Castle beside the ruined medieval Livonian Order castle.",
      "drive": "~1 hr from Riga",
      "parking": "Town lots.",
      "timing": "Pair with Turaida",
      "duration": "1–2 hrs",
      "photo": "castle_sigulda",
      "rec": "KEEP — pairs with Turaida.",
      "photo_key": "castle_sigulda",
      "photo_tip": "Cable-car views across the valley."
    },
    {
      "name": "Gauja National Park",
      "region": "Latvia",
      "why": "Latvia's largest national park — a forested river valley of sandstone cliffs, caves, and castles.",
      "drive": "Surrounds Sigulda/Turaida",
      "parking": "At trailheads.",
      "timing": "Jul 16",
      "duration": "As long as you like",
      "photo": "castle_gauja",
      "rec": "KEEP (drive-through).",
      "photo_key": "castle_gauja",
      "photo_tip": "River overlooks through the trees."
    },
    {
      "name": "Cēsis",
      "region": "Latvia",
      "why": "One of Latvia's best-preserved medieval castles, with candle-lantern tower tours.",
      "drive": "~1.5 hrs from Riga",
      "parking": "Town lots.",
      "timing": "Only if time allows",
      "duration": "1.5 hrs",
      "photo": "castle_cesis",
      "rec": "OPTIONAL — skip if starting at noon.",
      "photo_key": "castle_cesis",
      "photo_tip": "Castle ruins by candlelight."
    },
    {
      "name": "Hill of Crosses",
      "region": "Near Šiauliai, Lithuania",
      "why": "A pilgrimage mound bristling with well over 100,000 crosses — haunting symbol of Lithuanian faith.",
      "drive": "On the Riga→Vilnius route",
      "parking": "Free lot at the site.",
      "timing": "Jul 17",
      "duration": "30–45 min",
      "photo": "castle_hillofcrosses",
      "rec": "KEEP — the main transfer-day stop.",
      "photo_key": "castle_hillofcrosses",
      "photo_tip": "A wide shot of the cross-covered mounds."
    },
    {
      "name": "Trakai Castle",
      "region": "Lake Galvė, near Vilnius",
      "why": "A fairy-tale red-brick Gothic castle on an island in Lake Galvė, seat of the Grand Dukes.",
      "drive": "~30 min from Vilnius",
      "parking": "Lots near the lakefront.",
      "timing": "Jul 18, early or late for fewer crowds",
      "duration": "2–3 hrs",
      "photo": "castle_trakai",
      "rec": "KEEP — the Vilnius day trip. Try kibinai lakeside.",
      "photo_key": "castle_trakai",
      "photo_tip": "The castle across the water from the footbridge."
    }
  ],
  "budget": [
    {
      "item": "Flights — Michael's ticket",
      "amount_eur": null,
      "amount_usd": 1596.73,
      "status": "Confirmed",
      "note": "Ticket 057 236 023 779 2. Grace's ticket: UNCONFIRMED (open item)."
    },
    {
      "item": "Hotel Lilla Roberts (Helsinki, 1 night)",
      "amount_eur": 147.9,
      "amount_usd": 168.06,
      "status": "Confirmed",
      "note": ""
    },
    {
      "item": "Hotel Telegraaf (Tallinn, 4 nights)",
      "amount_eur": 1415.0,
      "amount_usd": null,
      "status": "Confirmed",
      "note": ""
    },
    {
      "item": "Grand Palace Hotel (Riga, 3 nights)",
      "amount_eur": 697.84,
      "amount_usd": null,
      "status": "Confirmed",
      "note": "Incl. taxes & fees."
    },
    {
      "item": "Hotel PACAI (Vilnius, 2 nights)",
      "amount_eur": 534.0,
      "amount_usd": null,
      "status": "Confirmed",
      "note": "Incl. taxes. Verify 2 adults."
    },
    {
      "item": "Rental car (EconomyBookings)",
      "amount_eur": null,
      "amount_usd": 550,
      "status": "Estimate",
      "note": "Cost not on screenshot; Michael estimated ≈ $500–600. PLUS fuel + one-way/cross-border fees."
    }
  ],
  "budget_unknowns": [
    "Grace's flight ticket (likely similar to Michael's ≈ USD 1,597 if separately issued).",
    "Rental car final total + one-way drop fee + cross-border fee + fuel.",
    "Ferry (Helsinki→Tallinn) and bus (Tallinn→Riga) fares — both unbooked.",
    "Meals, museum entries, taxis, and incidentals across 11 days.",
    "Parking in Riga and Vilnius Old Towns."
  ],
  "photos": {
    "city_helsinki": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Senate_Square_-_Senaatintori_-_Senatstorget%2C_Helsinki%2C_Finland.jpg/1280px-Senate_Square_-_Senaatintori_-_Senatstorget%2C_Helsinki%2C_Finland.jpg",
      "page": "https://commons.wikimedia.org/wiki/File:Senate_Square_-_Senaatintori_-_Senatstorget,_Helsinki,_Finland.jpg",
      "credit": "Matti Mattila",
      "license": "CC BY 2.0",
      "filename": "File:Senate Square - Senaatintori - Senatstorget, Helsinki, Finland.jpg"
    },
    "city_tallinn": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Old_car_and_old_city.jpg/1280px-Old_car_and_old_city.jpg",
      "page": "https://commons.wikimedia.org/wiki/File:Old_car_and_old_city.jpg",
      "credit": "Maasaak",
      "license": "CC BY-SA 3.0",
      "filename": "File:Old car and old city.jpg"
    },
    "city_riga": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Panorama_of_Riga%2C_1572_%28v2%29.jpg/1280px-Panorama_of_Riga%2C_1572_%28v2%29.jpg",
      "page": "https://commons.wikimedia.org/wiki/File:Panorama_of_Riga,_1572_(v2).jpg",
      "credit": "1581 Braun &amp; Hogenberg: of \"Civitates Orbis Terrarum.\"",
      "license": "Public domain",
      "filename": "File:Panorama of Riga, 1572 (v2).jpg"
    },
    "city_vilnius": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Panorama_of_the_Vilnius_Old_Town%2C_1944.jpg/1280px-Panorama_of_the_Vilnius_Old_Town%2C_1944.jpg",
      "page": "https://commons.wikimedia.org/wiki/File:Panorama_of_the_Vilnius_Old_Town,_1944.jpg",
      "credit": "Jan Bułhak",
      "license": "Public domain",
      "filename": "File:Panorama of the Vilnius Old Town, 1944.jpg"
    },
    "tallinn_st_catherine": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Pasaje_de_Santa_Catarina%2C_Tallin%2C_Estonia%2C_2012-08-05%2C_DD_01.JPG/1280px-Pasaje_de_Santa_Catarina%2C_Tallin%2C_Estonia%2C_2012-08-05%2C_DD_01.JPG",
      "page": "https://commons.wikimedia.org/wiki/File:Pasaje_de_Santa_Catarina,_Tallin,_Estonia,_2012-08-05,_DD_01.JPG",
      "credit": "Diego Delso",
      "license": "CC BY-SA 3.0",
      "filename": "File:Pasaje de Santa Catarina, Tallin, Estonia, 2012-08-05, DD 01.JPG"
    },
    "tallinn_town_hall": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Tallinn_-_Town_Hall_Square_%28Raekoja_plats%29.jpg/1280px-Tallinn_-_Town_Hall_Square_%28Raekoja_plats%29.jpg",
      "page": "https://commons.wikimedia.org/wiki/File:Tallinn_-_Town_Hall_Square_(Raekoja_plats).jpg",
      "credit": "Pudelek (Marcin Szala)",
      "license": "CC BY-SA 3.0 ee",
      "filename": "File:Tallinn - Town Hall Square (Raekoja plats).jpg"
    },
    "tallinn_viewpoint": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/View_of_Tallinn_old_town_1.jpg/1280px-View_of_Tallinn_old_town_1.jpg",
      "page": "https://commons.wikimedia.org/wiki/File:View_of_Tallinn_old_town_1.jpg",
      "credit": "kallerna",
      "license": "CC BY-SA 3.0",
      "filename": "File:View of Tallinn old town 1.jpg"
    },
    "tallinn_pikk": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Tallinn.-_26_Pikk_House_of_the_Brotherhood_of_Black_Heads_%281%29.JPG/1280px-Tallinn.-_26_Pikk_House_of_the_Brotherhood_of_Black_Heads_%281%29.JPG",
      "page": "https://commons.wikimedia.org/wiki/File:Tallinn.-_26_Pikk_House_of_the_Brotherhood_of_Black_Heads_(1).JPG",
      "credit": "Pierre André Leclercq",
      "license": "CC BY-SA 4.0",
      "filename": "File:Tallinn.- 26 Pikk House of the Brotherhood of Black Heads (1).JPG"
    },
    "riga_alberta": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Alberta_iel%C4%81_12_20120728-05.JPG/1280px-Alberta_iel%C4%81_12_20120728-05.JPG",
      "page": "https://commons.wikimedia.org/wiki/File:Alberta_iel%C4%81_12_20120728-05.JPG",
      "credit": "Hans A. Rosbach",
      "license": "CC BY-SA 3.0",
      "filename": "File:Alberta ielā 12 20120728-05.JPG"
    },
    "riga_blackheads": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/House_of_Blackheads_and_St._Peter%27s_Church_Tower%2C_Riga%2C_Latvia_-_Diliff.jpg/1280px-House_of_Blackheads_and_St._Peter%27s_Church_Tower%2C_Riga%2C_Latvia_-_Diliff.jpg",
      "page": "https://commons.wikimedia.org/wiki/File:House_of_Blackheads_and_St._Peter%27s_Church_Tower,_Riga,_Latvia_-_Diliff.jpg",
      "credit": "Diliff",
      "license": "CC BY-SA 3.0",
      "filename": "File:House of Blackheads and St. Peter's Church Tower, Riga, Latvia - Diliff.jpg"
    },
    "vilnius_pilies": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Pilies_Street_at_dusk%2C_Vilnius%2C_Lithuania_-_Diliff.jpg/1280px-Pilies_Street_at_dusk%2C_Vilnius%2C_Lithuania_-_Diliff.jpg",
      "page": "https://commons.wikimedia.org/wiki/File:Pilies_Street_at_dusk,_Vilnius,_Lithuania_-_Diliff.jpg",
      "credit": "Diliff",
      "license": "CC BY-SA 3.0",
      "filename": "File:Pilies Street at dusk, Vilnius, Lithuania - Diliff.jpg"
    },
    "vilnius_uzupis": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Prie_Men%C5%B3_inkubatoriaus.jpg/1280px-Prie_Men%C5%B3_inkubatoriaus.jpg",
      "page": "https://commons.wikimedia.org/wiki/File:Prie_Men%C5%B3_inkubatoriaus.jpg",
      "credit": "Stela",
      "license": "CC0",
      "filename": "File:Prie Menų inkubatoriaus.jpg"
    },
    "vilnius_cathedral": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/VilniusCathedral_square_2014.jpg/1280px-VilniusCathedral_square_2014.jpg",
      "page": "https://commons.wikimedia.org/wiki/File:VilniusCathedral_square_2014.jpg",
      "credit": "Abrget47j",
      "license": "CC BY-SA 3.0",
      "filename": "File:VilniusCathedral square 2014.jpg"
    },
    "vilnius_gediminas": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Vilnius_Modern_Skyline_At_Dusk%2C_Lithuania_-_Diliff.jpg/1280px-Vilnius_Modern_Skyline_At_Dusk%2C_Lithuania_-_Diliff.jpg",
      "page": "https://commons.wikimedia.org/wiki/File:Vilnius_Modern_Skyline_At_Dusk,_Lithuania_-_Diliff.jpg",
      "credit": "Diliff",
      "license": "CC BY-SA 3.0",
      "filename": "File:Vilnius Modern Skyline At Dusk, Lithuania - Diliff.jpg"
    },
    "helsinki_market": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Buildings_near_Kauppatori_and_Helsinki_Cathedral_20100825_1.jpg/1280px-Buildings_near_Kauppatori_and_Helsinki_Cathedral_20100825_1.jpg",
      "page": "https://commons.wikimedia.org/wiki/File:Buildings_near_Kauppatori_and_Helsinki_Cathedral_20100825_1.jpg",
      "credit": "DXR",
      "license": "CC BY-SA 4.0",
      "filename": "File:Buildings near Kauppatori and Helsinki Cathedral 20100825 1.jpg"
    },
    "helsinki_esplanadi": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Espan_puisto_2025-7_-_Marit_Henriksson.jpg/1280px-Espan_puisto_2025-7_-_Marit_Henriksson.jpg",
      "page": "https://commons.wikimedia.org/wiki/File:Espan_puisto_2025-7_-_Marit_Henriksson.jpg",
      "credit": "Marit Henriksson",
      "license": "CC BY-SA 4.0",
      "filename": "File:Espan puisto 2025-7 - Marit Henriksson.jpg"
    },
    "castle_turaida": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Turaida_Castle.JPG/1280px-Turaida_Castle.JPG",
      "page": "https://commons.wikimedia.org/wiki/File:Turaida_Castle.JPG",
      "credit": "Pudelek (Marcin Szala)",
      "license": "CC BY-SA 3.0",
      "filename": "File:Turaida Castle.JPG"
    },
    "castle_sigulda": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/The_new_Sigulda_castle_%282%29.JPG/1280px-The_new_Sigulda_castle_%282%29.JPG",
      "page": "https://commons.wikimedia.org/wiki/File:The_new_Sigulda_castle_(2).JPG",
      "credit": "PIERRE ANDRE LECLERCQ",
      "license": "CC BY-SA 4.0",
      "filename": "File:The new Sigulda castle (2).JPG"
    },
    "castle_gauja": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Gauja_River.jpg/1280px-Gauja_River.jpg",
      "page": "https://commons.wikimedia.org/wiki/File:Gauja_River.jpg",
      "credit": "VolodyaVoronin",
      "license": "CC BY-SA 4.0",
      "filename": "File:Gauja River.jpg"
    },
    "castle_cesis": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Cesis_Castle_2014-12-27_%282%29.jpg/1280px-Cesis_Castle_2014-12-27_%282%29.jpg",
      "page": "https://commons.wikimedia.org/wiki/File:Cesis_Castle_2014-12-27_(2).jpg",
      "credit": "Voll",
      "license": "CC BY-SA 4.0",
      "filename": "File:Cesis Castle 2014-12-27 (2).jpg"
    },
    "castle_hillofcrosses": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Kry%C5%BEi%C5%B3_kalnas_%28G%C3%B3ra_Krzy%C5%BCy%29.JPG/1280px-Kry%C5%BEi%C5%B3_kalnas_%28G%C3%B3ra_Krzy%C5%BCy%29.JPG",
      "page": "https://commons.wikimedia.org/wiki/File:Kry%C5%BEi%C5%B3_kalnas_(G%C3%B3ra_Krzy%C5%BCy).JPG",
      "credit": "Pudelek (Marcin Szala)",
      "license": "CC BY-SA 3.0",
      "filename": "File:Kryžių kalnas (Góra Krzyży).JPG"
    },
    "castle_trakai": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/2/29/Trakai-Troki.jpg",
      "page": "https://commons.wikimedia.org/wiki/File:Trakai-Troki.jpg",
      "credit": "Julo",
      "license": "CC BY-SA 3.0",
      "filename": "File:Trakai-Troki.jpg"
    },
    "hotel_telegraaf": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Hotel_Telegraaf_-_panoramio.jpg/1280px-Hotel_Telegraaf_-_panoramio.jpg",
      "page": "https://commons.wikimedia.org/wiki/File:Hotel_Telegraaf_-_panoramio.jpg",
      "credit": "Henrik Heino",
      "license": "CC BY 3.0",
      "filename": "File:Hotel Telegraaf - panoramio.jpg"
    },
    "hotel_grandpalace": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Riga_-_Grand_Palace_Hotel_-_panoramio.jpg/1280px-Riga_-_Grand_Palace_Hotel_-_panoramio.jpg",
      "page": "https://commons.wikimedia.org/wiki/File:Riga_-_Grand_Palace_Hotel_-_panoramio.jpg",
      "credit": "giggel",
      "license": "CC BY 3.0",
      "filename": "File:Riga - Grand Palace Hotel - panoramio.jpg"
    },
    "hotel_pacai": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Hotel_PACAI_in_Vilnius_%28Christmas%2C_2019%29.jpg/1280px-Hotel_PACAI_in_Vilnius_%28Christmas%2C_2019%29.jpg",
      "page": "https://commons.wikimedia.org/wiki/File:Hotel_PACAI_in_Vilnius_(Christmas,_2019).jpg",
      "credit": "Pofka",
      "license": "CC BY-SA 4.0",
      "filename": "File:Hotel PACAI in Vilnius (Christmas, 2019).jpg"
    },
    "hotel_lilla": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Hotel_Lilla_Roberts.jpg/1280px-Hotel_Lilla_Roberts.jpg",
      "page": "https://commons.wikimedia.org/wiki/File:Hotel_Lilla_Roberts.jpg",
      "credit": "Vadelmavene",
      "license": "CC BY-SA 4.0",
      "filename": "File:Hotel Lilla Roberts.jpg"
    },
    "rest_maiasmokk": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Tallinn_kohvik_Maiasmokk.jpg/1280px-Tallinn_kohvik_Maiasmokk.jpg",
      "page": "https://commons.wikimedia.org/wiki/File:Tallinn_kohvik_Maiasmokk.jpg",
      "credit": "Liilia Moroz",
      "license": "CC BY-SA 4.0",
      "filename": "File:Tallinn kohvik Maiasmokk.jpg"
    },
    "rest_oldehansa": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Olde_Hansa%2C_2006_%2801%29.jpg/1280px-Olde_Hansa%2C_2006_%2801%29.jpg",
      "page": "https://commons.wikimedia.org/wiki/File:Olde_Hansa,_2006_(01).jpg",
      "credit": "Bahnfrend",
      "license": "CC BY-SA 4.0",
      "filename": "File:Olde Hansa, 2006 (01).jpg"
    }
  },
  "city_photos": {
    "Helsinki": "city_helsinki",
    "Tallinn": "city_tallinn",
    "Riga": "city_riga",
    "Vilnius": "city_vilnius"
  },
  "packing": {
    "intro": "July in the Baltics is mild and very long-lit (sun up ~4:30 AM, down ~10:30 PM). Highs 19–24 °C / 66–75 °F, cool evenings 12–14 °C, with passing showers. You'll walk a lot of cobblestones. Pack light, in layers, for warm days and cool candlelit nights.",
    "shared": [
      "Light rain jacket / packable umbrella (showers come and go)",
      "Layers — a warm sweater or two for cool evenings",
      "EU power adapters (Type C/F, 230 V) + a multi-USB charger",
      "Battery pack for long wandering days",
      "Passports (valid 6+ months) + printed copies; both flight tickets saved offline",
      "This guide saved offline / printed; offline Google Maps for FI/EE/LV/LT",
      "Small daypack for the car days and castle climbs",
      "Reusable water bottle",
      "Basic meds: pain relief, blister plasters, motion-sickness (for the ferry), any prescriptions in original packaging",
      "Cards + a little euro cash for small cafés and markets",
      "Sunglasses (the light is long) and a light scarf"
    ],
    "shoes": "Genuinely comfortable, broken-in walking shoes are the single most important item — Old Town cobblestones are unforgiving. Plus one slightly nicer pair for the dressier dinners (Tchaikovsky, Seasons, Rozengrāls, Nineteen18 lean smart-casual).",
    "grace": [
      "A dressier outfit or two for the grand-hotel dinners and the candlelit cellars",
      "A wrap/pashmina for cool evenings and the ferry deck",
      "Comfortable flats for cobblestones; one elegant pair for dinner",
      "Sunhat for the open castle grounds (Turaida, Trakai)"
    ],
    "michael": [
      "A smart-casual layer (blazer or nice sweater) for the upscale dinners",
      "Driving comfort — the Riga→Vilnius day is ~4.5 hrs at the wheel",
      "Phone mount or plan for car navigation; download offline maps before pickup",
      "Copies of the car booking, licence, and insurance for the pickup desk"
    ],
    "leave": [
      "Heavy coats — July doesn't need them",
      "Voltage converters — modern US electronics handle 230 V; you only need the plug adapter",
      "Too many shoes — two pairs each is plenty",
      "A rigid plan — leave room to stumble"
    ]
  }
};
